# version: '3.8'

services:
  frontend:
    image: rakshit910/movie-recc-client:latest
    ports:
      - "80:80"
    restart: always
    networks:
      - movie_net_frontend_2_backend
    depends_on:
      - backend

  backend:
    image: rakshit910/movie-recc-server:latest
    ports:
      - "3000:3000"
    restart: always
    networks:
      - movie_net_frontend_2_backend
      - movie_net_backend_2_ml
    depends_on:
      - ml

  ml:
    image: rakshit910/movie-recc-ml-service:latest
    ports:
      - "8000:8000"
    restart: always
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - movie_net_backend_2_ml
    volumes:
      - ./ml/ml-100k:/app/ml-100k 

volumes:
  ml_data:

networks:
  movie_net_frontend_2_backend:
    driver: bridge
  movie_net_backend_2_ml:
    driver: bridge