# version: '3.8'

services:
  frontend:
    image: rakshit910/movie-recc-client:latest
    ports:
      - "80:80"
    restart: always

  backend:
    image: rakshit910/movie-recc-server:latest
    ports:
      - "3000:3000"
    restart: always

  ml:
    image: rakshit910/movie-recc-ml-service:latest
    ports:
      - "8000:8000"
    restart: always
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]