# version: '3.8'

services:
  frontend-service:
    image: prajyotshende/movie-recc-client:latest
    container_name: frontend-service
    ports:
      - "80:80"
    restart: always
    networks:
      - movie-recc-network
    depends_on:
      - backend-service

  backend-service:
    image: prajyotshende/movie-recc-server:latest
    container_name: backend-service
    ports:
      - "3000:3000"
    restart: always
    networks:
      - movie-recc-network
    depends_on:
      - ml-service

  ml-service:
    image: prajyotshende/movie-recc-ml-service:latest
    container_name: ml-service
    ports:
      - "8000:8000"
    restart: always
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./ml/ml-100k:/app/ml-100k
    networks:
      - movie-recc-network

networks:
  movie-recc-network:
    driver: bridge
