apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml
spec:
  replicas: 1                       # match your HPA minReplicas
  selector:
    matchLabels:
      app: ml
  template:
    metadata:
      labels:
        app: ml
    spec:

      initContainers:
      - name: seed-and-mkdir
        image: rakshit910/ml-data-seeder:latest
        command:
          - sh
          - -c
          - |
            # Mount the PVC on /data-root, prepare subdirs, seed once
            mkdir -p /data-root/ml-100k
            mkdir -p /data-root/model_data
            if [ -z "$(ls -A /data-root/ml-100k)" ]; then
              cp -r /ml-100k/* /data-root/ml-100k/
            fi
        volumeMounts:
          - name: data
            mountPath: /data-root
      - name: train-model
        image: rakshit910/movie-recc-ml-service:latest  # Python-enabled image
        command:
          - sh
          - -c
          - |
            mkdir -p /app/model_data
            python -c "from model_manager import model_manager; model_manager.train_model()"
        volumeMounts:
          - name: data
            mountPath: /app/ml-100k
            subPath: ml-100k
          - name: data
            mountPath: /app/model_data
            subPath: model_data

      containers:
      - name: ml
        image: rakshit910/movie-recc-ml-service:latest
        ports:
          - containerPort: 8000
        volumeMounts:
          # Mount only the ml-100k subdir into /app/ml-100k
          - name: data
            mountPath: /app/ml-100k
            subPath: ml-100k
          - name: data  # Add this
            mountPath: /app/model_data
            subPath: model_data

      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data-pvc
