---
- name: Deploy Frontend
  hosts: frontend
  become: yes
  roles:
    - frontend

- name: Deploy Backend
  hosts: backend
  become: yes
  roles:
    - backend

- name: Deploy ML Service
  hosts: ml
  become: yes
  roles:
    - ml
